version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    commit-message:
      prefix: "chore:"
    groups:
      gradle-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      gradle-major:
        patterns: ["*"]
        update-types: ["major"]
    open-pull-requests-limit: 5
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
    groups:
      actions-all:
        patterns: ["*"]  
