version: 2
updates:
  # --- Backend (Gradle) ---
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - ["dependencies", "gradle"]
    commit-message:
      prefix: "chore:"
    groups:
      gradle-minor-patch:
        patterns: ["*"]
        update-types: ["minor", "patch"]
      gradle-major:
        patterns: ["*"]
        update-types: ["major"]
    open-pull-requests-limit: 5
  
   # --- Frontend (npm) ---
  - package-ecosystem: "npm"
    directory: "/mps-web"
    schedule:
      interval: "monthly"
    versioning-strategy: increase
    labels: ["dependencies", "npm"]
    commit-message:
      prefix: "chore(npm):"
    open-pull-requests-limit: 5
    groups:
      npm-prod-minor-patch:
        dependency-type: "production"
        update-types: ["minor", "patch"]
        patterns: ["*"]
      npm-dev-minor-patch:
        dependency-type: "development"
        update-types: ["minor", "patch"]
        patterns: ["*"]
      npm-major:
        update-types: ["major"]
        patterns: ["*"]
