server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:mps}
    username: ${DB_USER:mps}
    password: ${DB_PASS:mps}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 5000
      pool-name: mps-api-pool
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        jdbc.time_zone: UTC
        hbm2ddl.create_namespaces: true