server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db}
    username: ${DB_USER:user}
    password: ${DB_PASS:pass}
    hikari:
      maximum-pool-size: 4
      minimum-idle: 2
      idle-timeout: 600000
      connection-timeout: 5000
      pool-name: mps-api-pool
    jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect